exports.USER_ROLES = {
  CUSTOMER: 'customer',
  EEON_CONTENT_ADMIN: 'eeon_content_admin',
  EEON_SUPER_ADMIN: 'eeon_super_admin',
}

exports.SORT_ORDER = {
  ASC: 'asc',
  DESC: 'desc',
}

exports.IEX_PERIOD = {
  ANNUAL: 'annual',
  QUARTERLY: 'quarterly',
}

/**
 * Maps to https://iexcloud.io/docs/api/#historical-prices
 */
exports.IEX_TIME_RANGES = {
  FIVE_DAYS: '5d',
  FIVE_YEARS: '5y',
  MAX: 'max',
  ONE_MONTH: '1m',
  ONE_YEAR: '1y',
  SIX_MONTHS: '6m',
  THREE_MONTHS: '3m',
  TWO_YEARS: '2y',
  YTD: 'ytd',
}

exports.IEX_TAGS = {
  ELECTRONIC_TECHNOLOGY: 'Electronic Technology',
  DISTRIBUTION_SERVICES: 'Distribution Services',
  COMMERCIAL_SERVICES: 'Commercial Services',
  HEALTH_TECHNOLOGY: 'Health Technology',
  INDUSTRIAL_SERVICES: 'Industrial Services',
  FINANCE: 'Finance',
  TRANSPORTATION: 'Transportation',
  PROCESS_INDUSTRIES: 'Process Industries',
  TECHNOLOGY_SERVICES: 'Technology Services',
  PRODUCER_MANUFACTURING: 'Producer Manufacturing',
  RETAIL_TRADE: 'Retail Trade',
  CONSUMER_SERVICES: 'Consumer Services',
  NON_ENERGY_MINERALS: 'Non-Energy Minerals',
  UTILITIES: 'Utilities',
  MISCELLANEOUS: 'Miscellaneous',
  HEALTH_SERVICES: 'Health Services',
  CONSUMER_DURABLES: 'Consumer Durables',
  CONSUMER_NON_DURABLES: 'Consumer Non-Durables',
  COMMUNICATIONS: 'Communications',
  ENERGY_MINERALS: 'Energy Minerals',
  HOMEBUILDING: 'Homebuilding',
  SEMICONDUCTORS: 'Semiconductors',
  OFFICE_EQUIPMENT_SUPPLIES: 'Office Equipment/Supplies',
  BIOTECHNOLOGY: 'Biotechnology',
  TOOLS_HARDWARE: 'Tools & Hardware',
  OILFIELD_SERVICES_EQUIPMENT: 'Oilfield Services/Equipment',
  OTHER_METALS_MINERALS: 'Other Metals/Minerals',
  INVESTMENT_MANAGERS: 'Investment Managers',
  DEPARTMENT_STORES: 'Department Stores',
  PACKAGED_SOFTWARE: 'Packaged Software',
  ELECTRONICS_APPLIANCE_STORES: 'Electronics/Appliance Stores',
  MEDICAL_SPECIALTIES: 'Medical Specialties',
  GAS_DISTRIBUTORS: 'Gas Distributors',
  INFORMATION_TECHNOLOGY_SERVICES: 'Information Technology Services',
  FOOD_SPECIALTY_CANDY: 'Food: Specialty/Candy',
  AUTO_PARTS_OEM: 'Auto Parts: OEM',
  CHEMICALS_SPECIALTY: 'Chemicals: Specialty',
  SPECIALTY_STORES: 'Specialty Stores',
  FOOD_RETAIL: 'Food Retail',
  ELECTRONICS_DISTRIBUTORS: 'Electronics Distributors',
  SAVINGS_BANKS: 'Savings Banks',
  FINANCE_RENTAL_LEASING: 'Finance/Rental/Leasing',
  WIRELESS_TELECOMMUNICATIONS: 'Wireless Telecommunications',
  AEROSPACE_DEFENSE: 'Aerospace & Defense',
  ADVERTISING_MARKETING_SERVICES: 'Advertising/Marketing Services',
  COMPUTER_COMMUNICATIONS: 'Computer Communications',
  CABLE_SATELLITE_TV: 'Cable/Satellite TV',
  DISCOUNT_STORES: 'Discount Stores',
  APPAREL_FOOTWEAR_RETAIL: 'Apparel/Footwear Retail',
  MOVIES_ENTERTAINMENT: 'Movies/Entertainment',
  CHEMICALS_AGRICULTURAL: 'Chemicals: Agricultural',
  ELECTRONICS_APPLIANCES: 'Electronics/Appliances',
  MAJOR_BANKS: 'Major Banks',
  PHARMACEUTICALS_OTHER: 'Pharmaceuticals: Other',
  CONSUMER_SUNDRIES: 'Consumer Sundries',
  INDUSTRIAL_SPECIALTIES: 'Industrial Specialties',
  COMPUTER_PERIPHERALS: 'Computer Peripherals',
  MISCELLANEOUS_MANUFACTURING: 'Miscellaneous Manufacturing',
  BEVERAGES_ALCOHOLIC: 'Beverages: Alcoholic',
  REAL_ESTATE_DEVELOPMENT: 'Real Estate Development',
  ELECTRONIC_EQUIPMENT_INSTRUMENTS: 'Electronic Equipment/Instruments',
  BUILDING_PRODUCTS: 'Building Products',
  INTERNET_SOFTWARE_SERVICES: 'Internet Software/Services',
  FOOD_DISTRIBUTORS: 'Food Distributors',
  OIL_GAS_PRODUCTION: 'Oil & Gas Production',
  HOSPITAL_NURSING_MANAGEMENT: 'Hospital/Nursing Management',
  PRECIOUS_METALS: 'Precious Metals',
  RECREATIONAL_PRODUCTS: 'Recreational Products',
  ELECTRONIC_COMPONENTS: 'Electronic Components',
  RESTAURANTS: 'Restaurants',
  ELECTRONIC_PRODUCTION_EQUIPMENT: 'Electronic Production Equipment',
  DATA_PROCESSING_SERVICES: 'Data Processing Services',
  OTHER_CONSUMER_SERVICES: 'Other Consumer Services',
  HOTELS_RESORTS_CRUISELINES: 'Hotels/Resorts/Cruiselines',
  APPAREL_FOOTWEAR: 'Apparel/Footwear',
  MEDICAL_DISTRIBUTORS: 'Medical Distributors',
  FOOD_MAJOR_DIVERSIFIED: 'Food: Major Diversified',
  MISCELLANEOUS_COMMERCIAL_SERVICES: 'Miscellaneous Commercial Services',
  ELECTRICAL_PRODUCTS: 'Electrical Products',
  AGRICULTURAL_COMMODITIES_MILLING: 'Agricultural Commodities/Milling',
  OTHER_CONSUMER_SPECIALTIES: 'Other Consumer Specialties',
  INVESTMENT_TRUSTS_MUTUAL_FUNDS: 'Investment Trusts/Mutual Funds',
  MAJOR_TELECOMMUNICATIONS: 'Major Telecommunications',
  HOUSEHOLD_PERSONAL_CARE: 'Household/Personal Care',
  METAL_FABRICATION: 'Metal Fabrication',
  FOOD_MEAT_FISH_DAIRY: 'Food: Meat/Fish/Dairy',
  TRUCKS_CONSTRUCTION_FARM_MACHINERY: 'Trucks/Construction/Farm Machinery',
  REGIONAL_BANKS: 'Regional Banks',
  COMMERCIAL_PRINTING_FORMS: 'Commercial Printing/Forms',
  MOTOR_VEHICLES: 'Motor Vehicles',
  PUBLISHING_NEWSPAPERS: 'Publishing: Newspapers',
  ENGINEERING_CONSTRUCTION: 'Engineering & Construction',
  PHARMACEUTICALS_MAJOR: 'Pharmaceuticals: Major',
  ENVIRONMENTAL_SERVICES: 'Environmental Services',
  REAL_ESTATE_INVESTMENT_TRUSTS: 'Real Estate Investment Trusts',
  TEXTILES: 'Textiles',
  WHOLESALE_DISTRIBUTORS: 'Wholesale Distributors',
  BROADCASTING: 'Broadcasting',
  MEDICAL_NURSING_SERVICES: 'Medical/Nursing Services',
  MEDIA_CONGLOMERATES: 'Media Conglomerates',
  HOME_IMPROVEMENT_CHAINS: 'Home Improvement Chains',
  CONTRACT_DRILLING: 'Contract Drilling',
  ELECTRIC_UTILITIES: 'Electric Utilities',
  INTERNET_RETAIL: 'Internet Retail',
  FINANCIAL_CONGLOMERATES: 'Financial Conglomerates',
  TOBACCO: 'Tobacco',
  TELECOMMUNICATIONS_EQUIPMENT: 'Telecommunications Equipment',
  INDUSTRIAL_MACHINERY: 'Industrial Machinery',
  CASINOS_GAMING: 'Casinos/Gaming',
  INVESTMENT_BANKS_BROKERS: 'Investment Banks/Brokers',
  CHEMICALS_MAJOR_DIVERSIFIED: 'Chemicals: Major Diversified',
  AIRLINES: 'Airlines',
  HOME_FURNISHINGS: 'Home Furnishings',
  CONTAINERS_PACKAGING: 'Containers/Packaging',
  DRUGSTORE_CHAINS: 'Drugstore Chains',
  CONSTRUCTION_MATERIALS: 'Construction Materials',
  AIR_FREIGHT_COURIERS: 'Air Freight/Couriers',
  FINANCIAL_PUBLISHING_SERVICES: 'Financial Publishing/Services',
  PERSONNEL_SERVICES: 'Personnel Services',
  BEVERAGES_NON_ALCOHOLIC: 'Beverages: Non-Alcoholic',
  STEEL: 'Steel',
  MARINE_SHIPPING: 'Marine Shipping',
  SERVICES_TO_THE_HEALTH_INDUSTRY: 'Services to the Health Industry',
  COMPUTER_PROCESSING_HARDWARE: 'Computer Processing Hardware',
  INDUSTRIAL_CONGLOMERATES: 'Industrial Conglomerates',
  SPECIALTY_TELECOMMUNICATIONS: 'Specialty Telecommunications',
  TRUCKING: 'Trucking',
  PHARMACEUTICALS_GENERIC: 'Pharmaceuticals: Generic',
  INSURANCE_BROKERS_SERVICES: 'Insurance Brokers/Services',
  WATER_UTILITIES: 'Water Utilities',
  PUBLISHING_BOOKS_MAGAZINES: 'Publishing: Books/Magazines',
  ALTERNATIVE_POWER_GENERATION: 'Alternative Power Generation',
  CATALOG_SPECIALTY_DISTRIBUTION: 'Catalog/Specialty Distribution',
  OIL_GAS_PIPELINES: 'Oil & Gas Pipelines',
  INTEGRATED_OIL: 'Integrated Oil',
  AUTOMOTIVE_AFTERMARKET: 'Automotive Aftermarket',
  ALUMINUM: 'Aluminum',
  PROPERTY_CASUALTY_INSURANCE: 'Property/Casualty Insurance',
  OIL_REFINING_MARKETING: 'Oil Refining/Marketing',
  MULTI_LINE_INSURANCE: 'Multi-Line Insurance',
  LIFE_HEALTH_INSURANCE: 'Life/Health Insurance',
  SPECIALTY_INSURANCE: 'Specialty Insurance',
  MANAGED_HEALTH_CARE: 'Managed Health Care',
  COAL: 'Coal',
  OTHER_TRANSPORTATION: 'Other Transportation',
  FOREST_PRODUCTS: 'Forest Products',
  PULP_PAPER: 'Pulp & Paper',
  RAILROADS: 'Railroads',
  SOVEREIGN: 'Sovereign',
  SUPRANATIONAL: 'Supranational',
  GENERAL_GOVERNMENT: 'General Government',
  GOVERNMENT: 'Government',
}

exports.IEX_TIMEFRAMES = {
  FIVE_YEARS: '5y',
  TWO_YEARS: '2y',
  ONE_YEAR: '1y',
  YTD: 'ytd',
  SIX_MONTHS: '6m',
  THREE_MONTHS: '3m',
  ONE_MONTH: '1m',
  NEXT: 'next',
}

exports.SPDR_SECTOR_ETFS = {
  SPY: 'S&P 500 Index',
  XLC: 'Communication Services',
  XLY: 'Consumer Discretionary',
  XLP: 'Consumer Staples',
  XLE: 'Energy',
  XLF: 'Financials',
  XLV: 'Health Care',
  XLI: 'Industrials',
  XLB: 'Materials',
  XLRE: 'Real Estate',
  XLK: 'Technology',
  XLU: 'Utilities',
}
